site_name: Publisher guide
nav:
    - Welcome: index.md
    - Getting started:
      - Configuring your account: gs/index.md
      - Publishing series: gs/series.md
      - Inviting collaborators: gs/members.md
      - Adding charts: gs/charts.md
      - Wrapping-up: gs/wrapup.md
    - Working in Excel:
      - Getting started: excel/index.md
      - Simple publication: excel/put.md
      - Batch publication: excel/batch.md
    - Going further:
      - Organising the collection: next/index.md
      - Creating a private collection: next/private.md
      - Building all charts: next/charts.md
      - Answering questions: next/questions.md
    - Working with the API:
      - Get started: api/index.md
      - Reference: api/reference.md
theme:
  name: material
  palette:
    primary: white
    secondary: black
    accent: orange
  logo: img/logo_statit_64.png
  favicon: img/favicon.ico
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.instant
    - navigation.tracking
extra:
  generator: false not working
  homepage: https://www.gostatit.com
  analytics:
    provider: google
    property: UA-163848470-1
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
